from .photo_handler import photo_message_handler
from .voice_handler import voice_message_handler
from .document_image_handler import document_image_handler
from .ai_handler import ai_message_handler, all_message_handler
from .charakter_handler import charakter_handler 